import type { NextPage } from "next";
import Head from "next/head";
import FormJob from "../components/FormJob";

const Home: NextPage = () => {
  const inputs = [
    {
      id: "email",
      title: "Email",
      type: "email",
      placeholder: "Type your email",
      pattern: ".+@*.com",
      required: true,
    },
    {
      id: "firstName",
      title: "First Name",
      type: "text",
      placeholder: "Type your first name",
      pattern: "",
      required: true,
    },
    {
      id: "lastName",
      title: "Last Name",
      type: "text",
      placeholder: "Type your last name",
      pattern: "",
      required: true,
    },
    {
      id: "role",
      title: "Role",
      type: "text",
      placeholder: "Type your role",
      pattern: "",
      required: true,
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />
      <FormJob />
    </div>
  );
};

export default Home;
